## Use whatever base image
FROM alpine

## Add the wait script to the image
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.9.0/wait /wait
RUN chmod +x /wait

## Add your application to the docker image
ADD account-service.sh /account-service.sh

## Launch the wait tool and then your application
CMD /wait && /account-service.sh

